In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [78]:
x = [5,10,10,10,17,25,15,30]
y = [5,10,5,10,10,25,5,10]

In [79]:
X = np.stack((x, y), axis = 1)
X = sorted(X, key=lambda x: x[0])
X

[array([5, 5]),
 array([10, 10]),
 array([10,  5]),
 array([10, 10]),
 array([15,  5]),
 array([17, 10]),
 array([25, 25]),
 array([30, 10])]

In [80]:
kmeans = KMeans(n_clusters=2, random_state = 1).fit(X)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 1, 1], dtype=int32)

In [81]:
kmeans.cluster_centers_

array([[11.16666667,  7.5       ],
       [27.5       , 17.5       ]])